# Generated by Django 3.0.3 on 2020-02-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
