# Generated by Django 3.0.3 on 2020-02-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_login_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avator',
            new_name='avatar',
        ),
    ]
