# Generated by Django 3.0.3 on 2020-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200212_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('comfirmed', 'Comfirmed'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
    ]
